apache:
  # Build from Dockerfile because we want to fix TimeZone as well as have httpd.conf and index.html cooked in it.
  build: apache/
  ports:
    - "80:80"
jenkins:
  # Build the jenkins image from the jenkins/ directory.
  # We need to do it because:
  #  (a) we need to add plugins to jenkins.
  #  (b) We need to fix the timezone in Dockerfile, which cannot be done at runtime.
  build: jenkins/
  ports: 
   - "8080:8080"
   - "50000:50000"
  volumes:
   - /opt/containers/jenkins_home:/var/jenkins_home 
  command: --prefix=/jenkins
artifactory:
  # Build artifactory image from the artifactory/ directory .
  # We need to do it because we need to fix the TimeZone, which can only be done in Dockerfile
  build: artifactory/
  ports:
   - "8090:8080"
  volumes:
   - /opt/containers/artifactory/data:/artifactory/data 
   - /opt/containers/artifactory/logs:/artifactory/logs 
   - /opt/containers/artifactory/backup:/artifactory/backup
  environment:
   - JAVA_OPTS='-Djsse.enableSNIExtension=false'


